[package]
name = "instrument_async"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.25.0"
chrometracer = { path = "../../chrometracer" }
